// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAu8uZMJOJCpKE-vrvqCa9p91b4xdlQw8w',
    appId: '1:720202559365:web:65706d47a11c14f2f65eec',
    messagingSenderId: '720202559365',
    projectId: 'se2-project-dca8b',
    authDomain: 'se2-project-dca8b.firebaseapp.com',
    storageBucket: 'se2-project-dca8b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAU1qN6sJRW4ood-e4yKipMLtU-SpjgO_0',
    appId: '1:720202559365:android:d4c6ddea7e7a266ef65eec',
    messagingSenderId: '720202559365',
    projectId: 'se2-project-dca8b',
    storageBucket: 'se2-project-dca8b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_waQLSuNeuZhqrUMdEQ78W8R4DYYch8Y',
    appId: '1:720202559365:ios:45e4963c4da07a2df65eec',
    messagingSenderId: '720202559365',
    projectId: 'se2-project-dca8b',
    storageBucket: 'se2-project-dca8b.appspot.com',
    iosBundleId: 'com.example.wajehny',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_waQLSuNeuZhqrUMdEQ78W8R4DYYch8Y',
    appId: '1:720202559365:ios:2e63013902c04214f65eec',
    messagingSenderId: '720202559365',
    projectId: 'se2-project-dca8b',
    storageBucket: 'se2-project-dca8b.appspot.com',
    iosBundleId: 'com.example.wajehny.RunnerTests',
  );
}
